### ISSUE TITLE
Joomla Extension Update Could Not Open Update Site

### ISSUE THREAD

**Issue by jsiepka** [ITPrism/PrismLibrary#2]
When using Joomla extension updates I receive the following warning

Update: Could not open update site #20 "ITPrism Library Updates ( from CDN )", URL: http://cdn.itprism.com/updates/itprism-library.xml

When I try to directly access http://cdn.itprism.com/updates/itprism-library.xml using a web browser I receive a 404 error.

**Comment by ITPrism** [comment]
Hi,
It is a link to ITPrism Library. It is not available any more. You should delete the address by your Update Manager.

**Comment by jsiepka** [comment]
That makes sense. I uninstalled the old library and installed the new one. Thanks for your help!
