### ISSUE TITLE
Huge problem with latest update

### ISSUE THREAD

**Issue by blackdoginet** [ITPrism/PrismLibrary#3]
Error displaying the error page: Class 'Prism\Container' not found: Class 'Prism\Container' not found

Updated modules online. Using ITPrism library for ITPMeta whole site is now down with above error message.
![screenshot from 2017-04-01 16 21 46](https://cloud.githubusercontent.com/assets/17192852/24579104/786717b2-16f7-11e7-96aa-2853b1561e8d.png)

**Comment by ITPrism** [comment]
Could you upgrade Prism Library, please?
http://itprism.com/free-joomla-extensions/others/software-development-kit
