### ISSUE TITLE
Joomla errors with Prism Library v.1.20

### ISSUE THREAD

**Issue by finetuning-mg** [ITPrism/PrismLibrary#5]
I am on Joomla 3.7.5 and Crowdfunding 2.6.5.

After installing Prism v1.20, every project page triggers this Joomla Error:

Catchable fatal error: Argument 2 passed to Prism\Money\Money::__construct() must be an instance of Prism\Money\Currency, none given, called in xxxxx/libraries/Crowdfunding/Container/MoneyHelper.php on line 123 and defined in xxxxx/libraries/Prism/Money/Money.php on line 49

The Crowdfinance main page triggers a similar error:

Catchable fatal error: Argument 2 passed to Prism\Money\Money::__construct() must be an instance of Prism\Money\Currency, none given, called in xxxxx/libraries/Crowdfunding/Helper/MoneyHelper.php on line 82 and defined in xxxxx/libraries/Prism/Money/Money.php on line 49

Reverting to Prism 1.19.6 fixes the issues

**Comment by ITPrism** [comment]
Hi,
Please, do not use Prism Library v1.20 with CF 2.6. 
It will be possible when I publish next release v2.7 :)
